server {
    server_name securechat.chickenkiller.com;

    location / {
        proxy_pass http://127.0.0.1:8000;
	add_header Strict-Transport-Security "max-age=31536000; includeSubDomains; preload" always;
	ssl_protocols TLSv1.2 TLSv1.3;
    }

    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/securechat.chickenkiller.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/securechat.chickenkiller.com/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

}
server {
    if ($host = securechat.chickenkiller.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    listen 80;
    server_name securechat.chickenkiller.com;
    return 404; # managed by Certbot

}
